FROM eclipse-temurin:21-jdk-jammy as base
RUN apt-get update && apt-get install -y dos2unix
WORKDIR /app

COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN dos2unix mvnw pom.xml
RUN ./mvnw dependency:resolve


FROM eclipse-temurin:21-jre-jammy as production
EXPOSE 8080
COPY --from=0 /app/target/dependency* /app/lib
COPY --from=0 /app/target/classes /app

WORKDIR /app
EXPOSE 8080
CMD ["./mvnw", "spring-boot:run"]
